import Head from 'next/head' 
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from 'graphql-request'

const graphqlcms = new GraphQLClient(
  "https://api-ap-south-1.graphcms.com/v2/cl42yjhtj4rz601xjenwt0pls/master"
)
const QUERY = gql`
{
  posts{
    id,
    title,
    slug,
    content{
      html
    },
    author{
      name,
      avatar{
        url
      }
    },
    thumbnail{
      url,
    }
  }
}`;

export async function getStaticProps(){
  const {posts} = await graphqlcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10
  };
}


export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map(post => (
          <div className={styles.post} key={post.id}>
            <h2 className={styles.postTitle}>
              <a href={`/posts/${post.slug}`}>{post.title}</a>
            </h2>
            <div className={styles.content} dangerouslySetInnerHTML={{ __html: post.content.html }} />
          </div>
        ))}
      </main>

    </div>
  )
}
